### ISSUE TITLE
cant get production push to show on android

### ISSUE THREAD

**Issue by talarari** [driftyco/ionic-service-push-client#13]
im sending a notification via gcm (not dev push), i do get the notification to the callback in ionic-push.js, but notification.alert is always undefined (even though the notification json i send has alert:"

so the following code never enters the condition

      // If we have the notification plugin, show this
      if(options.canShowAlert && notification.alert) {
        if (navigator.notification) {
          navigator.notification.alert(notification.alert);
        } else {
          // Browser version
          alert(notification.alert);
        }
      }

the alert prop on the notification in the request i send to the api is translated to a message prop on the notification object in the ngcordova push callback.
when i changed the code to use notification,message it works

**Comment by talarari** [comment]
any updates on this? this is a really small bug but working around it and returning false from the callback 
prevents the use of some cool features like auto navigating to a certain state.

**Comment by ericb** [comment]
@talarari Are you still having issues?

**Comment by talarari** [comment]
yes this is still broken.
i'm working around it by returning false to signal i'm going to handle the notification myself and i copied some of the code from this repo, but a fix would be great

**Comment by Ionitron** [comment]
Greetings @talarari!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
