### ISSUE TITLE
Scheduling notification doesn't work ?

### ISSUE THREAD

**Issue by Dosix** [driftyco/ionic-service-push-client#27]
Hello, 

I would schedule some notifications but it doesn't work :/ Anyone try to do this because i think the problem come from ionic.

I use Ionic's API 

Best regards,
Ludovic

**Comment by Ionitron** [comment]
Greetings @Dosix!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
